### ISSUE TITLE
cannot init terraform with an ARM64

### ISSUE THREAD

**Issue by rsaeba** [terraform-iaac/terraform-kubernetes-cert-manager#12]
Hey folks !
I have this issue with this module and a M1 MacOS when initializing terraform
```
Error: Incompatible provider version
 
Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
 
Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms.
Other versions of this provider may have different platforms supported.
```

Regarding Hashicorp's documentation, this is related to "template_file" that is deprecated, [follow this link](https://registry.terraform.io/providers/hashicorp/template/latest/docs)

Have you ever seen this and already consider a solution?

Thanks!

**Comment by bohdantverdyi** [comment]
Hey, this providers is not used anymore. I've deleted from version.tf this.

Please you new tag v2.4.2
