### ISSUE TITLE
Timeout while creating cluster issuer

### ISSUE THREAD

**Issue by RadhaKrishna0018** [terraform-iaac/terraform-kubernetes-cert-manager#14]
Hi I am getting timeout error while implementing this module error is attached below.

╷
│ Error: letsencrypt-prod failed to create kubernetes rest client for update of resource: Get "https://xxxxxx.gr7.us-east-1.eks.amazonaws.com/api?timeout=32s": dial tcp: lookup xxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com on 8.8.8.8:53: no such host
│
│   with module.cert-manager.kubectl_manifest.cluster_issuer[0],
│   on .terraform/modules/cert-manager/main.tf line 42, in resource "kubectl_manifest" "cluster_issuer":
│   42: resource "kubectl_manifest" "cluster_issuer" {

as this is my first time implementing this a little help on how to resolve this would be appreciated. 

Thanks.

**Comment by bohdantverdyi** [comment]
Hi, there is two possible issues.

1. You haven't configured kubectl provider.
2. You EKS cluster is private or whitelisted, and you don't have a access to him.
