### ISSUE TITLE
why use helm?

### ISSUE THREAD

**Issue by ayushin** [terraform-iaac/terraform-kubernetes-cert-manager#15]
Hi,

I wonder if you plan to rework this module to use kubectl provider directly without helm?

I guess this should be the main point of creating a terraform module for this to have a better / fine granularity control over certman resources and avoid helm overhead.

In fact terraform does what helm does only a bit better.

**Comment by bohdantverdyi** [comment]
Hi, my goal to rework this module only for kubernetes provider) 

But currently kubernetes provider doesn’t support plan\apply for kubernetes_manifest without cert-manager CDRs already installed in kubernetes cluster.  It's not possible to make module with only one plan/apply with kubernetes provider. I am waiting for new releases of kubernetes providers)

Isuue of using kubernetes-providers depens on this:
[This resource requires API access during planning time. This means the cluster has to be accessible at plan time and thus cannot be created in the same apply operation. We recommend only using this resource for custom resources or resources not yet fully supported by the provider.](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#before-you-use-this-resource)

kubectl provider for such big yamls as cert-manager, have an unexpected  bugs. 
I also don't like to use helm approach, but for now it works really smoothly and predictable.
