### ISSUE TITLE
No custom-fields can be add to the certificate

### ISSUE THREAD

**Issue by JaslynnWangTR** [terraform-iaac/terraform-kubernetes-cert-manager#21]
I have a use case when using venafi as issuer.

My venafi is set to enforce some mandatory custom fields on each new certificate. When applying using yaml file, custom fields can be set inside metadata like this

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-xxxx
  namespace: xxxx
  annotations:
    venafi.cert-manager.io/custom-fields: |-
      [
      ]

Can we add this "custom field" feature in the module? Or can we add a way to specify a yaml file directly for certificate just like what we are doing for cluster issuer?

Thanks!

**Comment by bohdantverdyi** [comment]
@JaslynnWangTR Hello, i added new release v2.5.1 with the possibilty to add annotations into certificate. Please try.
