### ISSUE TITLE
Labeling certificate manifests

### ISSUE THREAD

**Issue by ozobotnovako** [terraform-iaac/terraform-kubernetes-cert-manager#29]
Labels cannot be added to the certificate manifests. This prevents from configuring [solver selectors](https://cert-manager.io/docs/configuration/acme/#adding-multiple-solver-types).

If this feature would be welcome, I'd more than happy to create a PR.

**Comment by ozobotnovako** [comment]
Yes, I want to use the `matchLabels` selector. I can configure the solver, but I can't currently configure the label on the `Certificate` to use it properly.

**Comment by bohdantverdyi** [comment]
I think there is no any problems to add optional labels into certificate. Feel free to open PR.

**Comment by bohdantverdyi** [comment]
Thank you. Merged.
