### ISSUE TITLE
"no matches for kind "ClusterIssuer" in group "cert-manager.io"" With terraform plan

### ISSUE THREAD

**Issue by everspader** [terraform-iaac/terraform-kubernetes-cert-manager#3]
Hi, I am getting the following error when creating the `helm_release` for the `cert-manager` with the `ClusterIssuer` in the same `terraform apply` because the `plan` fails.

I did a bit of Googling around and it seems that it's because in the plan state, the CRDs are not yet installed so the error happens.

Is this a known issue and is there a way to circumvent it?

```hcl
│ Error: Failed to determine GroupVersionResource for manifest
│ 
│   with module.k8s_base.kubernetes_manifest.cluster_issuer,
│   on ../../modules/k8s_base/main.tf line 35, in resource "kubernetes_manifest" "cluster_issuer":
│   35: resource "kubernetes_manifest" "cluster_issuer" {
│ 
│ no matches for kind "ClusterIssuer" in group "cert-manager.io"
```

**Comment by bohdantverdyi** [comment]
Hello @everspader , are you trying to add ClusterIssuer outside of the module ? 

kubernetes_manifest doesn't support to run **plan & apply**, when helm_release is not deployed yet. 

You can use kubectl_manifest instead.
Also you can add your custom ClusterIssuer to module via **cluster_issuer_yaml** variable.

**Comment by benbonnet** [comment]
@bohdantverdyi sorry to dig out this one; having the same problem. Not trying to create the cluster issuer from outside, just using :
```
module "cert_manager" {
  source = "terraform-iaac/cert-manager/kubernetes"
  cluster_issuer_email = "myownemail@gmail.com"
  cluster_issuer_name = "cert-manager-global"
  cluster_issuer_private_key_secret_name = "cert-manager-private-key"
} 
```

But getting the following : `cert-manager-global failed to create kubernetes rest client for update of resource: resource [cert-manager.io/v1/ClusterIssuer] isn't valid for cluster, check the APIVersion and Kind fields are valid`

**Comment by bohdantverdyi** [comment]
@benbonnet looks like cert-manager wan't installed correctly. Can you try to reply , and check if cert-manager is running in you GKE

**Comment by bohdantverdyi** [comment]
Have you configured kubectl provider?

**Comment by bohdantverdyi** [comment]
it couldn’t connect to kube api. Problem on your side or in providers configuration ( helm, kubernetes, kubectl )

**Comment by benbonnet** [comment]
It happened on the very first apply (first it creates the cluster, node pool, etc..., then `provider "kubernetes"`, then `module "cert_manager"`)

```
provider "kubernetes" {
  host  = "https://${google_container_cluster.this.endpoint}"
  token = data.google_client_config.provider.access_token
  cluster_ca_certificate = base64decode(
    google_container_cluster.this.master_auth[0].cluster_ca_certificate,
  )
}

module "cert_manager" {
  source = "terraform-iaac/cert-manager/kubernetes"
  cluster_issuer_email = "myemail@gmail.com"
  cluster_issuer_name = "cert-manager-global"
  cluster_issuer_private_key_secret_name = "cert-manager-private-key"
}
```

Anyhow, next applies are super smooth and everything going super fine

**Comment by bohdantverdyi** [comment]
do you have helm & kubectl providers settings ?

**Comment by bohdantverdyi** [comment]
https://github.com/terraform-iaac/terraform-kubernetes-cert-manager#you-should-to-add-into-your-terraform-kubectl--helm--provider-configuration

**Comment by benbonnet** [comment]
yup, just above kubernetes

**Comment by bohdantverdyi** [comment]
i don't see **provier "kubectl"**

**Comment by bohdantverdyi** [comment]
anyway, next apply smooth. I think problem was with not ready nodes. Becuase cluster-issuer can't deploy if cert-manager pods it's not ready

**Comment by benbonnet** [comment]
ok my bad; confused about kubectl/kubernetes provider 
will retry from scratch with all
