### ISSUE TITLE
Error: cert-manager failed to create kubernetes rest client for update of resource: resource [cert-manager.io/v1/ClusterIssuer] isn't valid for cluster, check the APIVersion and Kind fields are valid

### ISSUE THREAD

**Issue by datenzar** [terraform-iaac/terraform-kubernetes-cert-manager#4]
Hi there,

I have an eks-cluster deployed and upon applying this module. I receive this error:

> │ Error: cert-manager failed to create kubernetes rest client for update of resource: resource [cert-manager.io/v1/ClusterIssuer] isn't valid for cluster, check the APIVersion and Kind fields are valid
> │ 
> │   with module.cert_manager.kubectl_manifest.cluster_issuer[0],
> │   on .terraform/modules/cert_manager/main.tf line 42, in resource "kubectl_manifest" "cluster_issuer":
> │   42: resource "kubectl_manifest" "cluster_issuer" {

To solve the issue, I can deactivate the issuer creation `cluster_issuer_create = false` and apply a ClusterIssuer in a second step (due to dependency constraints, like discussed [here](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1367#)).

Any chance that I can get this module working as planned?

**Comment by bohdantverdyi** [comment]
Hello @datenzar , i guess you don't have configuration for kubectl which are used in this module. 

I've updated readme, how to configure kubectl provider.

**Comment by bohdantverdyi** [comment]
Hello @datenzar , i guess you don't have configuration for kubectl custom provider which is used by this module. 

I've updated readme, how to configure kubectl provider.

**Comment by dwbrite** [comment]
A note for fools like me who find this thread and can't figure out what's wrong with their kubectl provider config: RTFM

> [Note: Unlike the Terraform Kubernetes Provider, this provider will load the KUBECONFIG file if the environment variable is set.](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs#configuration)

Use `load_config_file       = false` to prevent it from loading the KUBECONFIG (despite the host/ca/token arguments already being set)
